using CostMasterAI.ViewModels;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.Extensions.DependencyInjection; // Wajib untuk DI Extension
using System;
using Windows.System; // Penting untuk VirtualKey

namespace CostMasterAI.Views
{
    public sealed partial class RecipesPage : Page
    {
        // 1. Properti ViewModel (Read-Only)
        public RecipesViewModel ViewModel { get; }

        // 2. Constructor
        public RecipesPage()
        {
            this.InitializeComponent();

            // Ambil ViewModel dari Service Locator (App.xaml.cs) yang sudah di-setup DI
            // Container otomatis mengurus dependensi (AppDbContext & AIService)
            ViewModel = App.Current.Services.GetRequiredService<RecipesViewModel>();

            // Set DataContext agar Binding XAML berfungsi
            this.DataContext = ViewModel;
        }

        // 3. Event Handler: Tombol Lihat Detail (Pop-up ContentDialog)
        private async void ShowDetail_Click(object sender, RoutedEventArgs e)
        {
            if (ViewModel == null) return;

            // Minta ViewModel untuk generate string laporan
            string detailText = ViewModel.GenerateCostDetailString();

            // Buat Dialog
            ContentDialog dialog = new ContentDialog
            {
                XamlRoot = this.XamlRoot,
                Title = "Rincian Perhitungan Harga",
                CloseButtonText = "Tutup",
                DefaultButton = ContentDialogButton.Close
            };

            // Buat isi Dialog (ScrollViewer + TextBlock)
            var scrollViewer = new ScrollViewer { VerticalScrollBarVisibility = ScrollBarVisibility.Auto };
            var textBlock = new TextBlock
            {
                Text = detailText,
                FontFamily = new Microsoft.UI.Xaml.Media.FontFamily("Consolas, Courier New"),
                FontSize = 14,
                TextWrapping = TextWrapping.Wrap
            };

            scrollViewer.Content = textBlock;
            dialog.Content = scrollViewer;

            await dialog.ShowAsync();
        }

        // 4. Event Handler: Input Harga Manual (Tekan Enter di TextBox Harga)
        // Ini diperlukan untuk UX yang baik (update perhitungan margin saat Enter ditekan)
        private void OnPriceBoxKeyDown(object sender, Microsoft.UI.Xaml.Input.KeyRoutedEventArgs e)
        {
            if (e.Key == VirtualKey.Enter)
            {
                // Paksa update binding data dari TextBox ke ViewModel sebelum command jalan
                // Agar nilai yang baru diketik (tapi belum lost focus) terbaca oleh ViewModel
                var textBox = sender as TextBox;
                var binding = textBox?.GetBindingExpression(TextBox.TextProperty);
                binding?.UpdateSource();

                // Panggil command di ViewModel untuk menghitung ulang margin
                // Command: RecalculateMarginFromPriceCommand (Generated by RelayCommand)
                if (ViewModel.RecalculateMarginFromPriceCommand.CanExecute(null))
                {
                    ViewModel.RecalculateMarginFromPriceCommand.Execute(null);
                }

                // Hilangkan fokus dari TextBox agar keyboard menutup / user tahu input sudah diproses
                // FocusState.Programmatic memindahkan fokus ke Page itu sendiri
                this.Focus(FocusState.Programmatic);
            }
        }
    }
}
